[phases.setup]
nixPkgs = ["gcc", "gfortran"]
nixPkgs = ["python311", "pkg-config", "openssl", "libffi"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install --upgrade setuptools wheel"]
